---
repos:
  # Standard fille formatting / hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # See: https://github.com/pre-commit/pre-commit-hooks/releases
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        # We want to ignore any file that ends in `.secret`
        exclude: |
          (?x)^(
          .*\.secret$
          )$
      - id: check-yaml
      - id: check-json
        exclude: |
          (?x)^(
              ^.vscode/.*\.json
          )$
      - id: pretty-format-json
        exclude: |
          (?x)^(
              ^.vscode/.*\.json
          )$
        args:
          - --autofix
          # Note: this hook does not honor the .editorconfig value so
          #   they need to be kept in sync manually
          - --indent=4
          # Do not convert extended unicode characters to escape sequences
          # e.g. 🤖 -> \ud83e\udd16
          - --no-ensure-ascii

  # Fix any markdown issues
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint

  # Make sure python is well formed
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      # Lint, fixing what can be automatically fixed
      - id: ruff
        args: [--fix]
      # Format to ensure consistent style
      - id: ruff-format

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.12.1
    hooks:
      - id: zizmor

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.97.7
    hooks:
      - id: renovate-config-validator
        args: [--strict]
