# https://mise.jdx.dev/dev-tools/mise-lock.html#enabling-lockfiles
[settings]
# Push the MISE managed path to the front of the PATH variable
activate_aggressive = true
env_cache = true
exec_auto_install = true
github_attestations = true
lockfile = true
pin = true
slsa = true

lockfile_platforms = ["macos-arm64", "linux-x64"]


[hooks.enter]
shell = "zsh"
script = ['source "{{ config_root }}/.envrc"']

[hooks.leave]
run = """
unset PYTHONPATH
unset MODEM_USERNAME
unset MODEM_PASSWORD
"""
shell = "zsh"


[settings.python]
uv_venv_auto = "create|source" # create .venv if missing, then activate

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[tools]
# Going to let UV manage this since pyproject.toml already drives this
uv = "0.11.28"
ruff = "0.15.20"
ty = "0.0.58"


# Kube things
kube-linter = "0.8.3"
kube-score = "1.20.0"
kubeconform = "0.8.0"
pluto = "5.24.0"

# Docs
"pipx:kubediagrams" = "0.8.0"
# For NPM and markdown lint2
bun = "1.3.14"
markdownlint-cli2 = "0.23.0"

# General house keeping
prek = "0.4.8"
pinact = "4.1.0"
