{
 "title": "SB Exporter",
 "description": "Dashboard for Surfboard cable modems",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "exporter_instance",
    "label": "Modem",
    "query": {
     "query": "label_values(sb8200_modem_info,instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time since last reboot",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb8200_modem_uptime_seconds{instance=\"$exporter_instance\"}"
    }
   ]
  },
  {
   "title": "Modulation scheme by downstream channel",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sb8200_downstream_modulation_scheme_count{instance=\"$exporter_instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Percentage Downstream Channels Locked",
   "type": "gauge",
   "description": "Percentage of all downstream channels that have locked",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sb8200_downstream_channel_lock_status_count{lock_status=\"Locked\", instance=\"$exporter_instance\"}) or vector(0)) / clamp_min((sum(sb8200_downstream_channel_lock_status_count{instance=\"$exporter_instance\"}) or vector(0)), 1)"
    }
   ]
  },
  {
   "title": "Minimum Downstream SNR",
   "type": "stat",
   "description": "Assuming 256QAM modulation, [30dB is the minimum, 33dB or higher is recommended](https://pickmymodem.com/signal-levels-docsis-3-03-1-cable-modem/).",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(sb8200_downstream_snr_dbmv{instance=\"$exporter_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Modulation scheme by upstream channel",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sb8200_upstream_channel_type{instance=\"$exporter_instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Percentage Upstream Channels Locked",
   "type": "gauge",
   "description": "Percentage of all upstream channels that have locked",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sb8200_upstream_channel_lock_count{lock_status=\"Locked\", instance=\"$exporter_instance\"}) or vector(0)) / clamp_min((sum(sb8200_upstream_channel_lock_count{instance=\"$exporter_instance\"}) or vector(0)), 1)"
    }
   ]
  },
  {
   "title": "Assorted Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SN",
     "type": "stat",
     "description": "Modem Serial Number",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sb8200_modem_info{instance=\"$exporter_instance\"}",
       "legendFormat": "{{ serial_number }}"
      }
     ]
    },
    {
     "title": "Firmware",
     "type": "stat",
     "description": "Current modem firmware version string",
     "gridPos": { "h": 3, "w": 6, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sb8200_modem_info{instance=\"$exporter_instance\"}",
       "legendFormat": "{{ software_version }}"
      }
     ]
    },
    {
     "title": "Connection Standard",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sb8200_modem_info{instance=\"$exporter_instance\"}",
       "legendFormat": "{{docsis_version}}"
      }
     ]
    },
    {
     "title": "Security Protocol",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sb8200_startup_security_state{instance=\"$exporter_instance\", sb8200_startup_security_state=\"enabled\"}",
       "legendFormat": "{{comment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstream Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "timeseries",
   "description": "Receive modulation error ratio (RxMER). [The higher the MER, the cleaner the received signal.](https://www.intraway.com/blog/monitoring-DOCSIS-3.1)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sb8200_downstream_snr_dbmv{instance=\"$exporter_instance\"}",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "% Corrected Codewords per Second",
   "type": "timeseries",
   "description": "Based on data from the past 5 minutes, what percentage of codewords was successfully corrected per second?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  rate(sb8200_downstream_corrected_total{instance=~\"$exporter_instance\"}[5m])\n/\n  clamp_min(\n        rate(sb8200_downstream_uncorrectable_total{instance=~\"$exporter_instance\"}[5m])\n      +\n        rate(sb8200_downstream_corrected_total{instance=~\"$exporter_instance\"}[5m]),\n      0.000000001\n  )",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "% Uncorrectable Codewords per Second",
   "type": "timeseries",
   "description": "Based on data from the past 5 minutes, what percentage of codewords could not be corrected per second?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  rate(sb8200_downstream_uncorrectable_total{instance=~\"$exporter_instance\"}[5m])\n/\n  clamp_min(\n        rate(sb8200_downstream_uncorrectable_total{instance=~\"$exporter_instance\"}[5m])\n      +\n        rate(sb8200_downstream_corrected_total{instance=~\"$exporter_instance\"}[5m]),\n      0.000000001\n  )",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Downstream Channel Frequency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sb8200_downstream_frequency_hz{instance=~\"$exporter_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream Channel Power Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sb8200_downstream_power_dbmv{instance=~\"$exporter_instance\"}",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Upstream Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream Channel Frequency Info",
   "type": "table",
   "description": "Center frequency and width of each upstream channel ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sb8200_upstream_frequency_hz{instance=~\"$exporter_instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sb8200_upstream_ch_width_hz{instance=~\"$exporter_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Channel Power Level",
   "type": "timeseries",
   "description": "Power level per upstream/transmit channel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sb8200_upstream_power_dbmv{instance=~\"$exporter_instance\"}",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "SB Exporter Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SB Exporter Scrape Duration",
   "type": "timeseries",
   "description": "Time for each scrape page to return HTML",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "meta_request_duration_seconds_sum{instance=\"$exporter_instance\"}/meta_request_duration_seconds_count{instance=\"$exporter_instance\"}",
     "legendFormat": "{{scrape_target}}"
    }
   ]
  },
  {
   "title": "SB Exporter Scrape Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "meta_scrape_success{instance=~\"$exporter_instance\"}",
     "legendFormat": "overall"
    }
   ]
  },
  {
   "title": "Parse result by target",
   "type": "heatmap",
   "description": "For each section of HTML that metrics are parsed from, count of the number of scrape/parse cycles where data was as expected versus total. Values departing from 1.0 indicate scraped HTML didn't contain expected structure/data.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "(sum(meta_parse_result_total{parse_result=\"True\", instance=~\"$exporter_instance\"}) by (parse_target, parse_result)) \n/ \non(parse_target) group_left \nsum(meta_parse_result_total{instance=~\"$exporter_instance\"}) by (parse_target)",
     "legendFormat": "{{parse_target}}"
    }
   ]
  },
  {
   "title": "Parse result by target",
   "type": "timeseries",
   "description": "Just another way of presenting the same info",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(meta_parse_result_total{parse_result=\"True\",instance=~\"$exporter_instance\"}) by (parse_target))\n/\n(sum(meta_parse_result_total{instance=~\"$exporter_instance\"}) by (parse_target))\n\n",
     "legendFormat": "{{ parse_target }}"
    }
   ]
  }
 ]
}