{
 "title": "Connect Box",
 "description": "Dashboard for Compal CH7465LG cable modems (marketed as \"Connect Box\" by several carriers)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "query": "localhost" },
   { "name": "port", "query": "${VAR_PORT}" }
  ]
 },
 "panels": [
  {
   "title": "Provisioning Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "connectbox_provisioning_status{instance=\"$host:$port\"} == 1",
     "legendFormat": "{{ connectbox_provisioning_status }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "connectbox_uptime_seconds{instance=\"$host:$port\"}"
    }
   ]
  },
  {
   "title": "Minimum Downstream RxMER",
   "type": "stat",
   "description": "Assuming 256QAM modulation, [30dB is the minimum, 33dB or higher is recommended](https://pickmymodem.com/signal-levels-docsis-3-03-1-cable-modem/).",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "min(connectbox_downstream_rxmer_db{instance=\"$host:$port\"})"
    }
   ]
  },
  {
   "title": "Upstream Timeouts in Last Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(connectbox_upstream_timeouts_total{instance=\"$host:$port\"}[60m]))"
    }
   ]
  },
  {
   "title": "Tuner Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "connectbox_tuner_temperature_celsius{instance=\"$host:$port\"}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "count(connectbox_ethernet_client_speed_mbit{instance=\"$host:$port\"})",
     "legendFormat": "LAN"
    },
    {
     "expr": "count(connectbox_wifi_client_speed_mbit{instance=\"$host:$port\"})",
     "legendFormat": "Wi-Fi"
    }
   ]
  },
  {
   "title": "Assorted Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cable Modem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "connectbox_device_info{instance=\"$host:$port\"}",
       "legendFormat": "{{ cable_modem_status }}"
      }
     ]
    },
    {
     "title": "ISP",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "connectbox_device_info{instance=\"$host:$port\"}",
       "legendFormat": "{{ operator_id }}"
      }
     ]
    },
    {
     "title": "Connection Standard",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "connectbox_device_info{instance=\"$host:$port\"}",
       "legendFormat": "{{ docsis_mode }}"
      }
     ]
    },
    {
     "title": "Firmware",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "connectbox_device_info{instance=\"$host:$port\"}",
       "legendFormat": "{{ firmware_version }}"
      }
     ]
    },
    {
     "title": "Hardware Version",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "connectbox_device_info{instance=\"$host:$port\"}",
       "legendFormat": "{{ hardware_version }}"
      }
     ]
    }
   ]
  },
  { "title": "Downstream Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Downstream RxMER",
   "type": "graph",
   "description": "Receive modulation error ratio (RxMER). [The higher the MER, the cleaner the received signal.](https://www.intraway.com/blog/monitoring-DOCSIS-3.1)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(connectbox_downstream_rxmer_db{instance=\"$host:$port\"}[5m])",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Corrected Codewords per Second",
   "type": "graph",
   "description": "Based on data from the past 5 minutes, what percentage of codewords was successfully corrected per second?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(connectbox_downstream_codewords_corrected_total{instance=\"$host:$port\"}[5m]) / (rate(connectbox_downstream_codewords_unerrored_total{instance=\"$host:$port\"}[5m]) + rate(connectbox_downstream_codewords_corrected_total{instance=\"$host:$port\"}[5m]) + rate(connectbox_downstream_codewords_uncorrectable_total{instance=\"$host:$port\"}[5m]))",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Uncorrectable Codewords per Second",
   "type": "graph",
   "description": "Based on data from the past 5 minutes, what percentage of codewords could not be corrected per second?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(connectbox_downstream_codewords_uncorrectable_total{instance=\"$host:$port\"}[5m]) / (rate(connectbox_downstream_codewords_unerrored_total{instance=\"$host:$port\"}[5m]) + rate(connectbox_downstream_codewords_corrected_total{instance=\"$host:$port\"}[5m]) + rate(connectbox_downstream_codewords_uncorrectable_total{instance=\"$host:$port\"}[5m]))",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Downstream Channel Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "connectbox_downstream_frequency_hz{instance=\"$host:$port\"}",
     "legendFormat": "Ch. {{ channel_id}}"
    }
   ]
  },
  {
   "title": "Downstream Channel Power Level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "dBmV" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(connectbox_downstream_power_level_dbmv{instance=\"$host:$port\"}[5m])",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  { "title": "Upstream Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Timeouts per 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Timeouts" }
   ],
   "targets": [
    {
     "expr": "sum(increase(connectbox_upstream_timeouts_total{instance=\"$host:$port\"}[15m])) by (timeout_type)",
     "legendFormat": "{{ timeout_type }} timeout"
    }
   ]
  },
  {
   "title": "Upstream Channel Frequency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "connectbox_upstream_frequency_hz{instance=\"$host:$port\"}",
     "legendFormat": "Ch. {{ channel_id}}"
    }
   ]
  },
  {
   "title": "Upstream Channel Power Level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(connectbox_upstream_power_level_dbmv{instance=\"$host:$port\"}[5m])",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Temperature",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "connectbox_tuner_temperature_celsius{instance=\"$host:$port\"}",
       "legendFormat": "Tuner"
      },
      {
       "expr": "connectbox_temperature_celsius{instance=\"$host:$port\"}",
       "legendFormat": "Device"
      }
     ]
    }
   ]
  },
  { "title": "LAN Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Ethernet Client Connection Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "connectbox_ethernet_client_speed_mbit{instance=\"$host:$port\"}",
     "legendFormat": "{{ hostname }} ({{ ipv4_address }})"
    }
   ]
  },
  {
   "title": "Wi-Fi Client Connection Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "connectbox_wifi_client_speed_mbit{instance=\"$host:$port\"}",
     "legendFormat": "{{ hostname }} ({{ ipv4_address }})"
    }
   ]
  },
  {
   "title": "Connectbox Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connectbox Exporter Scrape Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "connectbox_scrape_duration_seconds{instance=\"$host:$port\"}",
       "legendFormat": "{{ extractor }}"
      },
      {
       "expr": "sum(connectbox_scrape_duration_seconds{instance=\"$host:$port\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Connectbox Exporter Scrape Success",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "connectbox_up{instance=\"$host:$port\"}",
       "legendFormat": "{{ extractor }}"
      }
     ]
    }
   ]
  }
 ]
}