---
name: Build and Push Container

on:
  # Should it be needed, allow manual triggering
  workflow_dispatch:
  # Allow calling from other GHA workflows.
  # See: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow
  workflow_call:

# Start with no permissions, then allow per job/action
permissions: {}

jobs:
  # Ideally, the release wouldn't be allowed to proceed if tests fail.
  # We need to handle the manual workflow_dispatch case, though so it doesn't
  #    hurt to have the tests run first, again.
  lint_test_python:
    uses: ./.github/workflows/ci_python_lint_and_test.yaml
    permissions:
      # Needed for the test job to run
      contents: read

  release_package:
    name: Build and Push Container
    runs-on: ubuntu-latest
    needs: lint_test_python
    ##
    # See: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to GitHub Container Registry
        id: login-ghcr
        # See: https://github.com/docker/login-action/releases
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          # See: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.description="Prometheus exporter for SB8200 cable modem stats"

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          # For now, I only have amd64 nodes in k8s cluster
          platforms: linux/amd64

          # Don't build/push on PRs
          push: ${{ github.event_name != 'pull_request' }}

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.build_date }}
            VCS_REF=${{ steps.meta.outputs.vcs_ref }}
            VERSION=${{ steps.meta.outputs.version }}
